//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joole.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int Product_ID { get; set; }
        public Nullable<int> Manufacturer_ID { get; set; }
        public Nullable<int> SubCategory_ID { get; set; }
        public Nullable<int> Document_ID { get; set; }
        public string Product_Name { get; set; }
        public byte[] Product_Image { get; set; }
        public string Manufacturer_Name { get; set; }
        public string Category_Name { get; set; }
        public string Model { get; set; }
        public Nullable<int> Model_Year { get; set; }
        public Nullable<int> Series { get; set; }
        public string Use_Type { get; set; }
        public string Application_Place { get; set; }
        public string Mounting_Location { get; set; }
        public string Accessories { get; set; }
        public Nullable<int> Fans_Airflow { get; set; }
        public Nullable<int> Fans_MaxPower { get; set; }
        public Nullable<int> Fans_MaxSpeed { get; set; }
        public Nullable<int> Fans_SeepDiameter { get; set; }
        public Nullable<int> TVs_ScreenSize { get; set; }
        public string TVs_Resolution { get; set; }
        public string TVs_Color { get; set; }
        public string TVs_Types { get; set; }
    
        public virtual tblDocuemnt tblDocuemnt { get; set; }
        public virtual tblManufacturer tblManufacturer { get; set; }
        public virtual tblSubCategory tblSubCategory { get; set; }
    }
}
