//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joole.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProperty
    {
        public int Property_ID { get; set; }
        public string Property_Name { get; set; }
        public bool IsType { get; set; }
        public bool IsTechSpec { get; set; }
    }
}
